---
title: "Prevalence of Lyme Disease in the US"
runtime: shiny
output: html_document
---

This R Markdown document is made interactive using Shiny. Unlike the more traditional workflow of creating static reports, you can now create documents that allow your readers to change the assumptions underlying your analysis and see the results immediately. 

To learn more, see [Interactive Documents](http://rmarkdown.rstudio.com/authoring_shiny.html).


```{r, echo=FALSE, message=FALSE, warning=FALSE}
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(magrittr))
suppressPackageStartupMessages(library(knitr))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(rgdal))
suppressPackageStartupMessages(library(rvest))
suppressPackageStartupMessages(library(maps))
suppressPackageStartupMessages(library(ggmap))
suppressPackageStartupMessages(library(shiny))

# loading and tidying data 
lyme.disease.counts <- read.csv("lyme.disease.dataset.csv") %>%
  tbl_df %>%
  rename("1992-1996" = X1992.1996, "1997-2001" = X1997.2001, "2002-2006" = X2002.2006, "2007-2011" =  X2007.2011, CountyFIPS = CountyCode, StateFIPS = StateCode) %>%
  gather("year.range", "counts", 5:8) %>%
  filter(StateName != "Hawaii") %>%
  filter(StateName != "Alaska")

# adding zeros to CountyFIPS so that 3 digits in order to merge 
lyme.disease.counts$CountyFIPS <- sprintf("%03d", lyme.disease.counts$CountyFIPS)

# pasting StateFIPS and CountyFIPS to get full FIPS code 
lyme.disease.counts$FIPS <- paste(lyme.disease.counts$StateFIPS, lyme.disease.counts$CountyFIPS, sep = "")

# Census 2010 
census2010 <- read.csv("Census2010StateCounty.csv") %>%
  tbl_df %>%
  rename("FIPS" = Geo_FIPS, "pop.density" = SE_T002_002, "tot.pop" = SE_T001_001) %>%
  mutate(pop.under.eighteen = SE_T008_002 + SE_T008_003 + SE_T008_004 + SE_T008_005) %>%
  mutate(per.pop.under.eighteen = ((pop.under.eighteen/tot.pop) * 100)) %>%
  select(FIPS, pop.density, per.pop.under.eighteen, tot.pop)

# converting to character to match types for join
census2010$FIPS <- as.character(census2010$FIPS)

# lyme counts by county joined with census data by county
lyme.counts.census <- inner_join(lyme.disease.counts, census2010, by = "FIPS") %>%
  mutate(prevalence = (counts/tot.pop) *100) %>%
  select(-CountyName, -StateFIPS, -CountyFIPS)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
## COUNTY LEVEL

# loading county level map of US

US.county <- readOGR(dsn=".", 
              layer="gz_2010_us_050_00_500k", 
              verbose=FALSE) 

US.county@data <- US.county@data %>% 
  mutate(county=paste(STATE,COUNTY,sep=""))

# Convert shapefile to ggplot'able object
US.county.map <- fortify(US.county, region="county") %>% 
  tbl_df()

# removes the leading zero in order to join id with FIPS
US.county.map$id <- as.integer(US.county.map$id)

# converting to character to match types for join
US.county.map$id <- as.character(US.county.map$id)

# joining county level lyme disease countys with US county geographical info and lightening the data set to run faster
lyme.counts.county.geo <- inner_join(lyme.counts.census, US.county.map, by = c("FIPS" = "id")) %>%
  select(-hole, -piece, -order, -counts, -tot.pop, -per.pop.under.eighteen, - pop.density)

# shiny select box 
inputPanel(
    selectInput("years", label = "Year",
              choices = c("1992-1996", "1997-2001", "2002-2006", "2007-2011"))
    )

# shiny map with select box for different year ranges
renderPlot({
  year.choices <- input$years 
  lyme.counts.county.geo <- filter(lyme.counts.county.geo, year.range==year.choices)
  
 ggplot(lyme.counts.county.geo, aes(x=long, y=lat, group=group, fill = log10(prevalence))) +
  geom_polygon() +
  geom_path(col="black", size=0) +
  coord_map() +
  scale_fill_continuous(low="white", high="lawngreen", name="Prevalence", na.value = "white") 
})

```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
## STATE LEVEL

# totaling state counts and state population to calculate state prevalence 
lyme.state.prevalence <- group_by(lyme.counts.census, StateName, year.range) %>%
  summarise(tot.counts = sum(counts, na.rm = TRUE), tot.state.pop = sum(tot.pop, na.rm = TRUE))

# montana had zero cases from 1992-2006, replacing zeros with NAs (since log10 of 0 in INF) in the plot set NA values to result in white  
lyme.state.prevalence$tot.counts[lyme.state.prevalence$tot.counts == 0] <- NA

# calculating prevalence
lyme.state.prevalence <- mutate(lyme.state.prevalence, prevalence = (tot.counts/tot.state.pop)* 100)

# State map of US in 2010 
US.state <- map_data("state") %>% 
  tbl_df()

# clean text function
clean.text <- function(text){
  text <- gsub("[^[:alnum:]]", "", text)
  text <- gsub(" ", "", text)
  text <- tolower(text)
  return(text)
}

# cleaning up state names
lyme.state.prevalence$StateName <- clean.text(lyme.state.prevalence$StateName)
US.state$region <- clean.text(US.state$region)


# inner join with state geographic data
lyme.counts.states.geo <- inner_join(lyme.state.prevalence, US.state, by = c("StateName" = "region")) %>%
  select(-order, -subregion) 

# shiny select box 
inputPanel(
    selectInput("years", label = "Year",
              choices = c("1992-1996", "1997-2001", "2002-2006", "2007-2011"))
    )

# shiny map with select box for different year ranges
renderPlot({
  year.choices <- input$years 
  lyme.counts.states.geo <- filter(lyme.counts.states.geo, year.range==year.choices)
  
 ggplot(lyme.counts.states.geo, aes(x=long, y=lat, group=group, fill = log10(prevalence))) +
  geom_polygon() +
  geom_path(col="black", size=0.05) +
  coord_map() +
  scale_fill_continuous(low="white", high="lawngreen", name="Prevalence", na.value = "white") 
})

```




